### ***************************
###       S Q L    L A B
###  S T U D E N T    F I L E 
### ***************************

USE supply_chain;


### 1. What is the lowest and highest date in Orders

select min(orderdate) as lowest_order_date , max(orderdate) as highest_order_date
from orders;                                  -- ( incase if only the highest and lowest date needed )

-- (if date of the highest and lowest of orders needeD)
select orderdate, max(totalamount) as highest_in_order
from orders
group by OrderDate
order by highest_in_order DESc limit 1;

select orderdate, min(totalamount) as lowest_in_order
from orders
group by OrderDate
order by lowest_in_order ASC limit 1;



### 2.	Display month and year wise count of the orders placed

SELECT 
    year(ORDERDATE) AS Order_Year,
    MONTH(OrderDate) AS Order_Month,
    COUNT(*) AS ORDERS_PLACED
FROM Orders
GROUP BY ORDER_YEAR , ORDER_MONTH;

### 3.	Which customers did not place any order.

SELECT C.Id,C.FirstName,C.LastName,C.City,C.Country,C.Phone,O.CustomerId
FROM CUSTOMER AS C
LEFT JOIN ORDERS AS O
ON C.ID = O.CUSTOMERID
WHERE O.CUSTOMERID IS NULL;


### 4.	Arrange the products based on high demand by the customer in year 2021.

-- SUMMING THE OI.QUANTITY TO CALCULATE THE DEMAND // 

SELECT 
    OI.ProductId,
    P.ProductName,
    SUM(OI.Quantity) AS ORDER_DEMAND,
    YEAR(O.OrderDate) AS ORDER_YEAR
FROM
orderitem AS OI
INNER JOIN orders AS O
ON O.Id = OI.OrderId
INNER JOIN product AS P 
ON P.Id = OI.ProductId
WHERE YEAR(O.OrderDate)= 2021
GROUP BY OI.ProductId , P.ProductName , YEAR(O.ORDERDATE)
ORDER BY ORDER_DEMAND DESC;

-- INCASE WE NEED TOP 10 OF HIGH DEMAND, USING LIMIT 10 , 

SELECT 
    OI.ProductId,
    P.ProductName,
    SUM(OI.Quantity) AS ORDER_DEMAND,
    YEAR(O.OrderDate) AS ORDER_YEAR
FROM
orderitem AS OI
INNER JOIN orders AS O
ON O.Id = OI.OrderId
INNER JOIN product AS P 
ON P.Id = OI.ProductId
WHERE YEAR(O.OrderDate) = 2021
GROUP BY OI.ProductId , P.ProductName , YEAR(O.ORDERDATE)
ORDER BY ORDER_DEMAND DESC LIMIT 10;



### 5. Which customer has placed the largest order (i.e. highest order amount)

-- a) using subquery 
SELECT 
    c.Id,
    CONCAT(C.FirstName,'  ',C.LastName) AS FULLNAME,
    c.Country,
    o.TotalAmount
FROM orders o
JOIN customer c
    ON o.CustomerId = c.Id
WHERE o.TotalAmount = (SELECT MAX(TotalAmount) FROM orders);

-- using groupby & order by

SELECT 
	  C.Id, CONCAT(C.FirstName,'  ',C.LastName) AS FULLNAME,C.CITY,C.Country,
      MAX(O.TotalAmount) AS HIGHEST_TOTAL_AMOUNT
FROM CUSTOMER C
JOIN ORDERS O 
ON C.ID = O.CUSTOMERID
GROUP BY C.ID,FULLNAME,C.CITY,C.COUNTRY
ORDER BY HIGHEST_TOTAL_AMOUNT DESC LIMIT 1;


### 6.	Display top 5 customers in terms of TOTAL amount spent 

SELECT 
	  C.Id, CONCAT(C.FirstName,'  ',C.LastName) AS FULLNAME,C.CITY,C.Country,
      sum(O.TotalAmount) AS HIGHEST_TOTAL_AMOUNT
FROM CUSTOMER C
JOIN ORDERS O 
ON C.ID = O.CUSTOMERID
GROUP BY C.ID,FULLNAME,C.CITY,C.COUNTRY
ORDER BY HIGHEST_TOTAL_AMOUNT DESC LIMIT 5;

### 7.	Find out top 3 suppliers in terms of revenue generated by their products.

SELECT S.Id,S.CompanyName,S.ContactName,CONCAT(S.City,' ',S.Country) AS LOCATION ,S.Phone,
	   P.ProductName,
       SUM(OI.UnitPrice * OI.Quantity) AS TOTAL_REVENUE
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P 
ON S.ID = P.SUPPLIERID
INNER JOIN orderitem AS OI 
ON P.ID = OI.ProductId
group by S.Id,S.CompanyName,S.ContactName, LOCATION ,S.Phone, P.ProductName
ORDER BY TOTAL_REVENUE DESC LIMIT 3;


-- USING RANK() WINDOWS 

SELECT * 
FROM (
      SELECT S.Id,S.CompanyName,S.ContactName,CONCAT(S.City,' ',S.Country) AS LOCATION ,S.Phone,
	   P.ProductName,
       SUM(OI.UnitPrice * OI.Quantity) AS TOTAL_REVENUE,
       RANK() OVER (ORDER BY SUM(OI.UnitPrice * OI.Quantity) DESC) AS RANK_NUM
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P 
ON S.ID = P.SUPPLIERID
INNER JOIN orderitem AS OI 
ON P.ID = OI.ProductId
group by S.Id,S.CompanyName,S.ContactName, LOCATION ,S.Phone, P.ProductName
) AS TOP_SUPPLIER
WHERE RANK_NUM <=3;


### 8.  Create a combined list to display customers and supplier list. The list shall contain following FIVE fields
###     TYPE ('CUSTOMER' or 'SUPPLIER'), Contact Name, City, Country, Phone

SELECT
    'CUSTOMER' AS TYPE,
    CONCAT(c.FirstName, ' ', c.LastName) AS ContactName,
    c.City,
    c.Country,
    c.Phone
FROM Customer c

UNION ALL

SELECT
    'SUPPLIER' AS TYPE,
    s.ContactName,
    s.City,
    s.Country,
    s.Phone
FROM Supplier s;



### 9. Are there any customers who ordered more than 10 different products in the single order

SELECT 
    C.Id,CONCAT(C.FirstName,' ',C.LastName) AS FULLNAME,C.City,C.Country,
    O.Id AS OrderId,
    COUNT(DISTINCT oi.ProductId) AS ORDERED_PRODUCT
FROM customer AS C
JOIN orders AS O ON C.Id = O.CustomerId
JOIN orderitem OI ON O.Id = OI.OrderId
GROUP BY C.Id, FULLNAME, C.City, C.Country, O.Id
HAVING ORDERED_PRODUCT > 10
ORDER BY ORDERED_PRODUCT DESC;


### 10. Company sells the product at different discounted rates. Refer actual product price in product table 
###    and selling price in the order item table. Find the total amount saved in each order then 
###    display the orders from highest to lowest amount saved. 


SELECT
    OI.OrderId AS ORDER_ID,
    SUM((OI.quantity * P.UnitPrice) - (OI.quantity * OI.UnitPrice)) AS AMOUNT_SAVED
FROM orderitem AS OI
JOIN product AS P
ON OI.ProductId = P.Id
group by OI.OrderId
ORDER BY AMOUNT_SAVED DESC ;


### 11.	 List the Suppliers such that there are no customers in the country of the supplier


SELECT
    S.Id AS SUPPLIER_ID,S.CompanyName,S.ContactName AS SUPPLIER_NAME, S.Country,C.ID AS CUSTOMER_ID
FROM Supplier S
LEFT JOIN Customer AS C
ON S.Country = C.Country
WHERE C.Id IS NULL;

### 12. Find out for which products, UK is dependent on other countries for the supply. 
###    List the countries which are supplying these products in the same list.

  
SELECT
	P.Id AS PRODUCT_ID,P.ProductName,
    CONCAT(C.FirstName, ' ', C.LastName) AS CUSTOMER_NAME,C.Country AS CUSTOMER_COUNTRY,
	S.Country AS SUPPLIER_COUNTRY
FROM Customer AS C
JOIN Orders AS O
ON C.Id = O.CustomerId
JOIN OrderItem AS OI
ON O.Id = OI.OrderId
JOIN Product AS P
ON OI.ProductId = P.Id
JOIN Supplier AS S
ON P.SupplierId = S.Id
WHERE C.Country = 'UK'
AND S.Country NOT IN ('UK');



### END
